name: mcp_example
description: Example usage of easy_api_annotations and easy_api_generator
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  easy_api_annotations:
    path: ../packages/easy_api_annotations
  dart_mcp: ^0.5.0
  shelf_plus: ^1.11.0
  stream_channel: ^2.1.0

dev_dependencies:
  build_runner: any
  easy_api_generator:
    path: ../packages/easy_api_generator
