// Generated CLI templates
//
// Produces a runnable command-line application that exposes annotated
// `@Tool` methods as `package:args` `CommandRunner` subcommands. Each
// containing class becomes a command group, each tool method becomes a
// subcommand, and each parameter becomes a CLI option (with the same
// validation as the MCP and REST artifacts).

import 'dart:convert';

import 'package:easy_api_generator/builder/template_utils.dart';

class CliTemplate {
  /// Generates the CLI application Dart source for the given tools.
  ///
  /// [tools] - List of tool definitions produced by McpBuilder.
  /// [appName] - Display name of the CLI binary (used in help text).
  /// [logErrors] - When true, full error messages and stack traces are
  ///   written to stderr before the generic error response.
  static String generate(
    List<Map<String, dynamic>> tools, {
    required String appName,
    bool logErrors = false,
  }) {
    final escapedAppName = escapeDartString(appName);

    // Group tools by containing class. Tools with no className are top-level.
    final byClass = <String?, List<Map<String, dynamic>>>{};
    for (final tool in tools) {
      final className = tool['className'] as String?;
      byClass.putIfAbsent(className, () => []).add(tool);
    }

    // Collect imports the same way the MCP template does so we can call into
    // the user's source classes.
    final sourceImports = <String, String>{};
    final listInnerImports = <String>{};
    for (final tool in tools) {
      final src = tool['sourceImport'] as String?;
      final alias = tool['sourceAlias'] as String?;
      if (src != null && alias != null) sourceImports[src] = alias;
      final params = tool['parameters'] as List<Map<String, dynamic>>? ?? [];
      for (final p in params) {
        final imp = p['listInnerTypeImport'] as String?;
        if (imp != null) listInnerImports.add(imp);
      }
    }

    final listInnerImportStatements = listInnerImports
        .map((u) => "import '$u';")
        .join('\n');
    final sourceImportStatements = sourceImports.entries
        .map((e) => "import '${e.key}' as ${e.value};")
        .join('\n');

    // Generate the Command class for each tool.
    final toolCommandClasses = <String>[];
    // Class-group commands and their registrations.
    final classGroupClasses = <String>[];
    final mainRegistrations = <String>[];

    byClass.forEach((className, classTools) {
      if (className == null) {
        // Top-level functions become top-level commands.
        for (final tool in classTools) {
          toolCommandClasses.add(_renderToolCommand(tool, logErrors));
          mainRegistrations.add(
            '  runner.addCommand(${_toolCommandClassName(tool)}());',
          );
        }
        return;
      }

      final groupName = kebabCase(className);
      final groupClassName = '_${className}GroupCommand';
      final subRegs = <String>[];
      for (final tool in classTools) {
        toolCommandClasses.add(_renderToolCommand(tool, logErrors));
        subRegs.add('    addSubcommand(${_toolCommandClassName(tool)}());');
      }

      classGroupClasses.add('''
class $groupClassName extends Command<int> {
  @override
  String get name => '${escapeDartString(groupName)}';
  @override
  String get description => 'Commands for $className.';

  $groupClassName() {
${subRegs.join('\n')}
  }
}
''');
      mainRegistrations.add('  runner.addCommand($groupClassName());');
    });

    final logErrorsLine = 'const bool _logErrors = $logErrors;';

    // Determine whether any parameter requires JSON decoding so we can
    // conditionally include the _readJsonValue helper without triggering
    // unused-element warnings.
    var needsJsonHelper = false;
    for (final tool in tools) {
      final params = tool['parameters'] as List<Map<String, dynamic>>? ?? [];
      for (final p in params) {
        final type = p['type'] as String;
        final base = baseType(type);
        if (isCustomList(type) ||
            (!isPrimitive(type) && !isPrimitiveList(type) && base != 'bool')) {
          needsJsonHelper = true;
          break;
        }
      }
      if (needsJsonHelper) break;
    }

    final readJsonHelper = needsJsonHelper
        ? '''
/// Reads a JSON value from a CLI option. Accepts either a literal JSON
/// string or a curl-style `@path/to/file.json` reference.
dynamic _readJsonValue(String? raw) {
  if (raw == null || raw.isEmpty) return null;
  final src = raw.startsWith('@')
      ? io.File(raw.substring(1)).readAsStringSync()
      : raw;
  return jsonDecode(src);
}
'''
        : '';

    return '''
// Generated CLI app
// DO NOT EDIT - automatically generated by mcp_generator

import 'dart:async';
import 'dart:convert';
import 'dart:io' as io;

import 'package:args/args.dart';
import 'package:args/command_runner.dart';

$listInnerImportStatements
$sourceImportStatements

$logErrorsLine

Future<void> main(List<String> argv) async {
  final runner = CommandRunner<int>(
    '$escapedAppName',
    'Generated CLI for annotated easy_api tools.',
  );
  runner.argParser.addFlag(
    'compact',
    negatable: false,
    help: 'Emit results as compact (single-line) JSON instead of pretty-printed.',
  );
${mainRegistrations.join('\n')}

  try {
    final code = await runner.run(argv) ?? 0;
    io.exit(code);
  } on UsageException catch (e) {
    io.stderr.writeln(e);
    io.exit(64);
  }
}

$readJsonHelper

/// Serializes [result] for stdout. Defaults to pretty-printed JSON; with
/// the global `--compact` flag, emits single-line JSON.
void _emitResult(Object? result, ArgResults? globalResults) {
  if (result == null) return;
  Object? toEmit;
  try {
    if (result is num || result is bool || result is String) {
      toEmit = result;
    } else if (result is Map) {
      toEmit = result;
    } else if (result is List) {
      toEmit = result.map(_toJsonish).toList();
    } else {
      toEmit = _toJsonish(result);
    }
  } catch (_) {
    toEmit = result.toString();
  }
  final compact = globalResults != null && globalResults['compact'] == true;
  final encoded = compact
      ? jsonEncode(toEmit)
      : const JsonEncoder.withIndent('  ').convert(toEmit);
  io.stdout.writeln(encoded);
}

Object? _toJsonish(Object? e) {
  if (e == null || e is num || e is bool || e is String || e is Map) return e;
  if (e is List) return e.map(_toJsonish).toList();
  try {
    final tj = (e as dynamic).toJson;
    if (tj != null && tj is Function) return tj();
  } catch (_) {}
  return e.toString();
}

/// Reports a CLI usage / validation error and returns exit code 64.
int _usageError(String message) {
  io.stderr.writeln(message);
  return 64;
}

/// Reports an internal error and returns exit code 1.
int _internalError(Object e, StackTrace st, String name) {
  if (_logErrors) {
    io.stderr.writeln('[easy_api] \$name: \$e');
    io.stderr.writeln(st);
  }
  io.stderr.writeln('An error occurred while processing the request.');
  return 1;
}

${classGroupClasses.join('\n')}

${toolCommandClasses.join('\n')}
''';
  }

  /// Returns the synthetic class name used for a tool's `Command` subclass.
  ///
  /// Class methods become `_<ClassName><MethodName>Command`, top-level
  /// functions become `_<MethodName>Command`. Both forms are guaranteed to
  /// be unique because tool method names are validated as Dart identifiers
  /// during extraction.
  static String _toolCommandClassName(Map<String, dynamic> tool) {
    final methodName = tool['methodName'] as String? ?? tool['name'] as String;
    final className = tool['className'] as String?;
    final methodPart = pascalCase(methodName);
    if (className != null) {
      return '_$className${methodPart}Command';
    }
    return '_${methodPart}Command';
  }

  /// Returns the kebab-case subcommand name for a tool.
  ///
  /// For class methods this is the bare method name (the class is already
  /// the command group). For top-level functions, the resolved tool name
  /// is used as-is so server-level prefixes carry through.
  static String _toolSubcommandName(Map<String, dynamic> tool) {
    final className = tool['className'] as String?;
    if (className != null) {
      final methodName =
          tool['methodName'] as String? ?? tool['name'] as String;
      return kebabCase(methodName);
    }
    return kebabCase(tool['name'] as String);
  }

  /// Returns the kebab-case CLI option name for a parameter, honoring
  /// `@Parameter(alias:)` when set.
  static String _optionName(Map<String, dynamic> p) {
    final alias = p['parameterMetadata']?['alias'] as String?;
    return kebabCase(alias ?? (p['name'] as String));
  }

  /// Renders a single tool's `Command` subclass.
  static String _renderToolCommand(Map<String, dynamic> tool, bool logErrors) {
    final commandClassName = _toolCommandClassName(tool);
    final subcommandName = _toolSubcommandName(tool);
    final description = (tool['description'] as String?) ?? 'Tool';
    final params = tool['parameters'] as List<Map<String, dynamic>>? ?? [];

    final argRegistrations = params.map(_renderArgRegistration).join('\n');
    final argExtractions = params.map(_renderArgExtraction).join('\n');
    final validations = params
        .map(_renderArgValidation)
        .where((s) => s.isNotEmpty)
        .join('\n');

    // When the tool takes no parameters, suppress the unused_local_variable
    // warning for the local `r` reference.
    final rDecl = params.isEmpty
        ? '      // ignore: unused_local_variable\n      final r = argResults!;'
        : '      final r = argResults!;';

    // Build the call to the underlying tool method.
    final isAsync = tool['isAsync'] == true;
    final className = tool['className'] as String?;
    final isStatic = tool['isStatic'] == true;
    final sourceAlias = tool['sourceAlias'] as String? ?? 'lib';
    final methodName = tool['methodName'] as String? ?? tool['name'] as String;
    final callArgs = _callArgs(params);

    String invocation;
    if (className != null && isStatic) {
      invocation = '$sourceAlias.$className.$methodName($callArgs)';
    } else if (className != null) {
      invocation = '$sourceAlias.$className().$methodName($callArgs)';
    } else {
      invocation = '$sourceAlias.$methodName($callArgs)';
    }
    final awaitedInvocation = isAsync ? 'await $invocation' : invocation;

    final argParserBlock = params.isEmpty
        ? ''
        : '    argParser\n$argRegistrations;';

    return '''
class $commandClassName extends Command<int> {
  @override
  String get name => '${escapeDartString(subcommandName)}';
  @override
  String get description => '${escapeDartString(description)}';

  $commandClassName() {
$argParserBlock
  }

  @override
  Future<int> run() async {
    try {
$rDecl
$argExtractions
$validations
      final result = $awaitedInvocation;
      _emitResult(result, globalResults);
      return 0;
    } catch (e, st) {
      return _internalError(e, st, '${escapeDartString(subcommandName)}');
    }
  }
}
''';
  }

  /// Renders the `argParser.addX(...)` call for a single parameter.
  static String _renderArgRegistration(Map<String, dynamic> p) {
    final type = p['type'] as String;
    final base = baseType(type);
    final optName = _optionName(p);
    final isOptional = p['isOptional'] == true;
    final mandatory = !isOptional;
    final metadata = p['parameterMetadata'] as Map<String, dynamic>?;
    final descRaw = (metadata?['description'] as String?) ?? '';
    final help = escapeDartString(descRaw);
    final enumValues = metadata?['enumValues'] as List?;

    if (base == 'bool') {
      // Booleans use addFlag. defaultsTo can be deduced from defaultValueCode.
      final defaultCode = p['defaultValueCode'] as String?;
      final defaultsTo = (defaultCode == 'true' || defaultCode == 'false')
          ? defaultCode
          : 'false';
      return '      ..addFlag(\'${escapeDartString(optName)}\', '
          'negatable: true, defaultsTo: $defaultsTo, '
          'help: \'$help\')';
    }

    if (isPrimitiveList(type)) {
      return '      ..addMultiOption(\'${escapeDartString(optName)}\', '
          'help: \'$help\')';
    }

    final allowedExpr = (enumValues != null && enumValues.isNotEmpty)
        ? ', allowed: ${_dartListLiteral(enumValues)}'
        : '';
    final mandatoryExpr = mandatory ? ', mandatory: true' : '';
    String valueHelp;
    if (isCustomList(type)) {
      valueHelp = ', valueHelp: \'json-array-or-@file\'';
    } else if (!isPrimitive(type)) {
      // Custom class / Map / dynamic
      valueHelp = ', valueHelp: \'json-or-@file\'';
    } else {
      valueHelp = '';
    }
    return '      ..addOption(\'${escapeDartString(optName)}\''
        '$mandatoryExpr$allowedExpr$valueHelp, help: \'$help\')';
  }

  /// Renders the value-extraction snippet for a single parameter.
  ///
  /// The result is one or more Dart statements that resolve [r] (the
  /// parameter's `argResults!`) into a local variable named after the
  /// parameter's Dart name (so the call site can pass it through unchanged).
  static String _renderArgExtraction(Map<String, dynamic> p) {
    final paramName = p['name'] as String;
    final type = p['type'] as String;
    final base = baseType(type);
    final optName = _optionName(p);
    final isOptional = p['isOptional'] == true;
    final defaultCode = p['defaultValueCode'] as String?;

    String fallback() => defaultCode ?? 'null';

    if (base == 'bool') {
      // addFlag always returns bool (defaults to the configured default).
      return '      final $paramName = r[\'${escapeDartString(optName)}\'] as bool;';
    }

    if (isPrimitiveList(type)) {
      final inner = extractListInnerType(type);
      switch (inner) {
        case 'int':
          return '      final $paramName = ((r[\'${escapeDartString(optName)}\'] as List?) ?? const <String>[])'
              '.map((e) => int.parse(e as String)).toList();';
        case 'double':
          return '      final $paramName = ((r[\'${escapeDartString(optName)}\'] as List?) ?? const <String>[])'
              '.map((e) => double.parse(e as String)).toList();';
        case 'num':
          return '      final $paramName = ((r[\'${escapeDartString(optName)}\'] as List?) ?? const <String>[])'
              '.map((e) => num.parse(e as String)).toList();';
        case 'bool':
          return '      final $paramName = ((r[\'${escapeDartString(optName)}\'] as List?) ?? const <String>[])'
              '.map((e) => e.toString().toLowerCase() == \'true\').toList();';
        case 'String':
        default:
          return '      final $paramName = List<String>.from((r[\'${escapeDartString(optName)}\'] as List?) ?? const <String>[]);';
      }
    }

    if (base == 'String') {
      if (isOptional) {
        return '      final $paramName = (r[\'${escapeDartString(optName)}\'] as String?) ?? ${fallback()};';
      }
      return '      final $paramName = r[\'${escapeDartString(optName)}\'] as String;';
    }

    if (base == 'int' || base == 'double' || base == 'num') {
      final parser = base == 'int'
          ? 'int.parse'
          : base == 'double'
          ? 'double.parse'
          : 'num.parse';
      final raw = '(r[\'${escapeDartString(optName)}\'] as String?)';
      if (isOptional) {
        return '      final $paramName = $raw == null ? ${fallback()} : $parser($raw!);';
      }
      return '      final $paramName = $parser($raw!);';
    }

    // Custom class / List<custom> / Map / dynamic — read JSON and either
    // construct via fromJson or pass the decoded value through.
    if (isCustomList(type)) {
      final inner = extractListInnerType(type);
      final decoded =
          '(_readJsonValue(r[\'${escapeDartString(optName)}\'] as String?) as List?)';
      if (isOptional) {
        return '      final $paramName = $decoded == null ? ${fallback()} : '
            '$decoded!.map((e) => $inner.fromJson(e as Map<String, dynamic>)).toList();';
      }
      return '      final $paramName = '
          '$decoded!.map((e) => $inner.fromJson(e as Map<String, dynamic>)).toList();';
    }

    // Single custom class / Map / dynamic.
    final raw =
        '_readJsonValue(r[\'${escapeDartString(optName)}\'] as String?)';
    if (base == 'Map' ||
        base.startsWith('Map<') ||
        base == 'dynamic' ||
        base == 'Object') {
      if (isOptional) {
        return '      final $paramName = $raw ?? ${fallback()};';
      }
      return '      final $paramName = $raw;';
    }

    // Assume the type has a static `fromJson(Map<String, dynamic>)`.
    if (isOptional) {
      return '      final $paramName = $raw == null ? ${fallback()} : '
          '$base.fromJson($raw as Map<String, dynamic>);';
    }
    return '      final $paramName = '
        '$base.fromJson($raw as Map<String, dynamic>);';
  }

  /// Renders the validation snippet for a single parameter, mirroring the
  /// constraints applied by the MCP and REST templates.
  static String _renderArgValidation(Map<String, dynamic> p) {
    final paramName = p['name'] as String;
    final isOptional = p['isOptional'] == true;
    final metadata = p['parameterMetadata'] as Map<String, dynamic>?;
    if (metadata == null) return '';

    final out = <String>[];

    if (metadata.containsKey('maxLength')) {
      final maxLength = metadata['maxLength'] as int;
      final guard = isOptional
          ? '$paramName != null && $paramName.length > $maxLength'
          : '$paramName.length > $maxLength';
      out.add(
        '      if ($guard) {\n'
        '        return _usageError(\'Parameter $paramName exceeds maximum length of $maxLength characters.\');\n'
        '      }',
      );
    }

    if (metadata.containsKey('pattern')) {
      final pattern = metadata['pattern'] as String;
      final guard = isOptional
          ? '$paramName != null && !RegExp(r\'$pattern\').hasMatch($paramName)'
          : '!RegExp(r\'$pattern\').hasMatch($paramName)';
      out.add(
        '      if ($guard) {\n'
        '        return _usageError(\'Parameter $paramName does not match required pattern.\');\n'
        '      }',
      );
    }

    if (metadata.containsKey('minimum')) {
      final min = metadata['minimum'];
      final guard = isOptional
          ? '$paramName != null && $paramName < $min'
          : '$paramName < $min';
      out.add(
        '      if ($guard) {\n'
        '        return _usageError(\'Parameter $paramName must be >= $min.\');\n'
        '      }',
      );
    }

    if (metadata.containsKey('maximum')) {
      final max = metadata['maximum'];
      final guard = isOptional
          ? '$paramName != null && $paramName > $max'
          : '$paramName > $max';
      out.add(
        '      if ($guard) {\n'
        '        return _usageError(\'Parameter $paramName must be <= $max.\');\n'
        '      }',
      );
    }

    return out.join('\n');
  }

  /// Builds the Dart argument list for the underlying tool invocation.
  static String _callArgs(List<Map<String, dynamic>> params) {
    return params
        .map((p) {
          final name = p['name'] as String;
          final isNamed = p['isNamed'] == true;
          return isNamed ? '$name: $name' : name;
        })
        .join(', ');
  }

  /// Renders a Dart list literal from a list of literal JSON values.
  /// Used for the `allowed:` parameter on `addOption`.
  static String _dartListLiteral(List<dynamic> values) {
    final items = values
        .map((v) {
          if (v is String) return '\'${escapeDartString(v)}\'';
          return jsonEncode(v);
        })
        .join(', ');
    return '[$items]';
  }
}
