// OpenAPI Dart REST server template generator.

import 'package:easy_api_generator/builder/template_utils.dart';

/// Generates a standalone REST API server (shelf_plus) whose
/// endpoints match the OpenAPI specification already produced as `.openapi.json`.
class OpenApiDartTemplate {
  /// Generates the `.openapi.dart` REST server source code.
  ///
  /// [tools] — tool definitions from the builder (with sourceImport, sourceAlias, etc.)
  /// [port] — HTTP port to bind to
  /// [address] — HTTP bind address
  /// [openApiSpec] — the already-built OpenAPI 3.0 spec map
  /// [logErrors] — when `true`, writes detailed exceptions + stack traces to
  ///   `stderr` while still returning a generic 500 body to the client.
  ///   Mirrors `@Server(logErrors:)` behavior in the MCP templates.
  static String generate(
    List<Map<String, dynamic>> tools,
    int port,
    String address,
    Map<String, dynamic> openApiSpec, {
    bool logErrors = false,
  }) {
    // ── Source imports (aliased, same pattern as HttpTemplate) ──────────
    final sourceImports = <String, String>{};
    for (final tool in tools) {
      final sourceImport = tool['sourceImport'] as String?;
      final sourceAlias = tool['sourceAlias'] as String?;
      if (sourceImport != null && sourceAlias != null) {
        sourceImports[sourceImport] = sourceAlias;
      }
    }
    final sourceImportStatements = sourceImports.entries
        .map((e) => "import '${e.key}' as ${e.value};")
        .join('\n');

    // ── Build a name→tool lookup ───────────────────────────────────────
    final toolByName = <String, Map<String, dynamic>>{};
    for (final tool in tools) {
      toolByName[tool['name'] as String] = tool;
    }

    // ── Parse openApiSpec paths to build route list ────────────────────
    final paths = openApiSpec['paths'] as Map<String, dynamic>? ?? {};

    // We collect route registrations and handler functions.
    // Routes are split into two buckets so we can register fixed-segment
    // routes (like /users/search) before parameterized ones (/users/<id>).
    final fixedRoutes = <String>[];
    final paramRoutes = <String>[];
    final handlers = <String>[];
    final handlerNames = <String>{};

    for (final pathEntry in paths.entries) {
      final openApiPath = pathEntry.key;
      final methods = pathEntry.value as Map<String, dynamic>;

      // Extract resource name from first path segment for unique param naming.
      // e.g. /users/{id} → resource = 'users', /todos/{id} → resource = 'todos'
      final segments = openApiPath
          .split('/')
          .where((s) => s.isNotEmpty && !s.startsWith('{'))
          .toList();
      final resource = segments.isNotEmpty ? segments.first : 'item';

      // Convert {param} → <resourceParam> for shelf_router to ensure
      // unique parameter names across all routes (shelf_router requirement).
      final paramRenames = <String, String>{};
      final shelfPath = openApiPath.replaceAllMapped(RegExp(r'\{(\w+)\}'), (m) {
        final origName = m.group(1)!;
        final uniqueName =
            '$resource${origName[0].toUpperCase()}${origName.substring(1)}';
        paramRenames[origName] = uniqueName;
        return '<$uniqueName>';
      });

      final isParameterized = shelfPath.contains('<');

      for (final methodEntry in methods.entries) {
        final httpMethod = methodEntry.key; // get, post, patch, delete
        final operation = methodEntry.value as Map<String, dynamic>;
        final operationId = operation['operationId'] as String?;
        if (operationId == null) continue;

        final lookupKey = (operation['x-tool-name'] as String?) ?? operationId;
        final tool = toolByName[lookupKey];
        if (tool == null) continue;

        // Build a unique handler function name
        final handlerFnName = '_handle_${httpMethod}_${_sanitize(operationId)}';
        if (handlerNames.contains(handlerFnName)) continue;
        handlerNames.add(handlerFnName);

        // Route registration
        final routeLine =
            "  app.${httpMethod.toLowerCase()}('$shelfPath', $handlerFnName);";
        if (isParameterized) {
          paramRoutes.add(routeLine);
        } else {
          fixedRoutes.add(routeLine);
        }

        // Build handler
        handlers.add(
          _buildHandler(
            handlerFnName: handlerFnName,
            httpMethod: httpMethod.toUpperCase(),
            tool: tool,
            operation: operation,
            openApiPath: openApiPath,
            paramRenames: paramRenames,
          ),
        );
      }
    }

    // ── Address expression ───────────────────────────────────────────
    final addressExpression = "'${escapeDartString(address)}'";

    // ── Assemble generated code ────────────────────────────────────────
    final allRoutes = [...fixedRoutes, ...paramRoutes].join('\n');

    return '''
// AUTO-GENERATED by easy_api_generator — DO NOT EDIT

import 'dart:async';
import 'dart:convert';
import 'dart:io' as io;

import 'package:shelf_plus/shelf_plus.dart';

$sourceImportStatements

/// When true, detailed exceptions and stack traces are written to stderr.
/// User-facing 500 responses remain generic regardless of this flag.
const bool _logErrors = $logErrors;

void main() => shelfRun(init, defaultBindPort: $port, defaultBindAddress: $addressExpression);

Handler init() {
  var app = Router().plus;

$allRoutes

  return app.call;
}

${handlers.join('\n\n')}

dynamic _serializeResult(dynamic result) {
  if (result == null) return null;
  try {
    if (result is Map) return result;
    if (result is List) {
      return result.map((e) {
        if (e == null) return null;
        if (e is Map) return e;
        try {
          final toJson = e.toJson;
          if (toJson != null && toJson is Function) return toJson();
        } catch (_) {}
        return e.toString();
      }).toList();
    }
    final toJson = result.toJson;
    if (toJson != null && toJson is Function) return toJson();
    return result.toString();
  } catch (_) {
    return result.toString();
  }
}
''';
  }

  /// Sanitizes a name for use as a Dart identifier.
  static String _sanitize(String name) {
    return name.replaceAll(RegExp(r'[^a-zA-Z0-9_]'), '_');
  }

  /// Builds a handler function for a single route.
  static String _buildHandler({
    required String handlerFnName,
    required String httpMethod,
    required Map<String, dynamic> tool,
    required Map<String, dynamic> operation,
    required String openApiPath,
    required Map<String, String> paramRenames,
  }) {
    final params = tool['parameters'] as List<Map<String, dynamic>>? ?? [];
    final isAsync = tool['isAsync'] == true;
    final className = tool['className'] as String?;
    final isStatic = tool['isStatic'] == true;
    final sourceAlias = tool['sourceAlias'] as String? ?? 'lib';
    final methodName = tool['methodName'] as String? ?? tool['name'] as String;

    // Determine where parameters come from based on HTTP method + OpenAPI spec
    final parameterSpecs = operation['parameters'] as List<dynamic>? ?? [];
    final hasRequestBody = operation.containsKey('requestBody');

    // Build parameter extraction lines
    final extractionLines = <String>[];

    // Identify path parameters from OpenAPI spec
    final pathParamNames = <String>{};
    for (final spec in parameterSpecs) {
      final specMap = spec as Map<String, dynamic>;
      if (specMap['in'] == 'path') {
        pathParamNames.add(specMap['name'] as String);
      }
    }

    // Identify query parameters from OpenAPI spec
    final queryParamNames = <String>{};
    for (final spec in parameterSpecs) {
      final specMap = spec as Map<String, dynamic>;
      if (specMap['in'] == 'query') {
        queryParamNames.add(specMap['name'] as String);
      }
    }

    // If there's a request body, we need to parse it
    if (hasRequestBody) {
      extractionLines.add(
        '    final body = await request.body.asJson as Map<String, dynamic>;',
      );
    }

    // Extract each tool parameter
    for (final param in params) {
      final paramName = param['name'] as String;
      final paramType = param['type'] as String;
      final isOptional = param['isOptional'] == true;
      // Use alias as external name (query key, body key, path key) when present
      final externalName =
          (param['parameterMetadata']?['alias'] as String?) ?? paramName;

      if (pathParamNames.contains(externalName)) {
        // Path parameter — always comes as String from shelf_router
        final uniqueParamName = paramRenames[externalName] ?? externalName;
        extractionLines.add(
          _buildPathParamExtraction(
            paramName,
            paramType,
            isOptional,
            uniqueParamName,
          ),
        );
      } else if (queryParamNames.contains(externalName)) {
        // Query parameter
        extractionLines.add(
          _buildQueryParamExtraction(
            paramName,
            externalName,
            paramType,
            isOptional,
          ),
        );
      } else if (hasRequestBody) {
        // Body parameter
        extractionLines.add(
          _buildBodyParamExtraction(
            paramName,
            externalName,
            paramType,
            isOptional,
          ),
        );
      } else {
        // Fallback: try query params
        extractionLines.add(
          _buildQueryParamExtraction(
            paramName,
            externalName,
            paramType,
            isOptional,
          ),
        );
      }
    }

    // Build the method call
    final callArgs = _buildCallArgs(params);
    String call;
    if (className != null && isStatic) {
      call = '$sourceAlias.$className.$methodName($callArgs)';
    } else if (className != null) {
      call = '$sourceAlias.$className().$methodName($callArgs)';
    } else {
      call = '$sourceAlias.$methodName($callArgs)';
    }
    if (isAsync) {
      call = 'await $call';
    }

    // Determine response status code
    final statusCode = _statusCodeForMethod(httpMethod);
    final isNoContent = statusCode == 204;

    // Build the response
    String responseCode;
    if (isNoContent) {
      // For DELETE: generate return-type-aware handler
      final returnType = (tool['returnType'] as String?) ?? 'void';
      final baseReturnType = returnType.endsWith('?')
          ? returnType.substring(0, returnType.length - 1)
          : returnType;
      final isNullable = returnType.endsWith('?');

      if (baseReturnType == 'bool') {
        // Case 1: bool return — check for false
        responseCode =
            '''
      final result = $call;
      if (!result) {
        return Response.notFound(
          jsonEncode({'error': 'Resource not found'}),
          headers: {'Content-Type': 'application/json'},
        );
      }
      return Response($statusCode);''';
      } else if (isNullable) {
        // Case 2: nullable return — check for null
        responseCode =
            '''
      final result = $call;
      if (result == null) {
        return Response.notFound(
          jsonEncode({'error': 'Resource not found'}),
          headers: {'Content-Type': 'application/json'},
        );
      }
      return Response($statusCode);''';
      } else {
        // Case 3: void or non-nullable — just call and return 204
        responseCode =
            '''
      $call;
      return Response($statusCode);''';
      }
    } else {
      responseCode =
          '''
      final result = $call;
      final serialized = _serializeResult(result);
      return Response($statusCode,
        body: jsonEncode(serialized),
        headers: {'Content-Type': 'application/json'},
      );''';
    }

    final extractionBlock = extractionLines.join('\n');

    // Build handler signature with path params using unique names suffixed as `Param`
    final pathParamArgs = pathParamNames.map((name) {
      final uniqueName = paramRenames[name] ?? name;
      return ', String ${uniqueName}Param';
    }).join();

    return '''
Future<Response> $handlerFnName(Request request$pathParamArgs) async {
  try {
$extractionBlock
$responseCode
  } catch (e, st) {
    if (_logErrors) {
      io.stderr.writeln('[easy_api] $handlerFnName: \$e');
      io.stderr.writeln(st);
      await io.stderr.flush();
    }
    return Response.internalServerError(
      body: jsonEncode({'error': 'An error occurred while processing the request'}),
      headers: {'Content-Type': 'application/json'},
    );
  }
}''';
  }

  static int _statusCodeForMethod(String method) {
    switch (method) {
      case 'POST':
        return 201;
      case 'DELETE':
        return 204;
      default:
        return 200;
    }
  }

  static String _buildPathParamExtraction(
    String name,
    String type,
    bool isOptional,
    String uniqueName,
  ) {
    // shelf_router passes path params as positional String arguments.
    // The handler signature uses `${uniqueName}Param` to avoid shadowing.
    final conversion = _convertFromString(name, type, '${uniqueName}Param');
    return '    $conversion';
  }

  static String _buildQueryParamExtraction(
    String name,
    String externalName,
    String type,
    bool isOptional,
  ) {
    final rawExpr =
        "request.url.queryParameters['${escapeDartString(externalName)}']";
    if (isOptional) {
      final conversion = _convertFromStringNullable(name, type, rawExpr);
      return '    $conversion';
    }
    // Required query param: explicit null guard returning 400
    final lines = StringBuffer();
    lines.writeln('    final ${name}Raw = $rawExpr;');
    lines.writeln('    if (${name}Raw == null) {');
    lines.writeln('      return Response(400,');
    lines.writeln(
      "        body: jsonEncode({'error': \"Missing required query parameter '${escapeDartString(externalName)}'\"}),",
    );
    lines.writeln("        headers: {'Content-Type': 'application/json'},");
    lines.writeln('      );');
    lines.writeln('    }');
    final conversion = _convertFromString(name, type, '${name}Raw');
    lines.write('    $conversion');
    return lines.toString();
  }

  static String _buildBodyParamExtraction(
    String name,
    String externalName,
    String type,
    bool isOptional,
  ) {
    final baseType = type.endsWith('?')
        ? type.substring(0, type.length - 1)
        : type;

    if (isOptional) {
      switch (baseType) {
        case 'int':
          return "    final $name = body['${escapeDartString(externalName)}'] != null ? (body['${escapeDartString(externalName)}'] as num).toInt() : null;";
        case 'double':
          return "    final $name = body['${escapeDartString(externalName)}'] != null ? (body['${escapeDartString(externalName)}'] as num).toDouble() : null;";
        case 'bool':
          return "    final $name = body['${escapeDartString(externalName)}'] as bool?;";
        case 'String':
          return "    final $name = body['${escapeDartString(externalName)}'] as String?;";
        default:
          if (baseType.startsWith('List<')) {
            return '    final $name = body[\'${escapeDartString(externalName)}\'] as List<dynamic>?;';
          }
          return "    final $name = body['${escapeDartString(externalName)}'];";
      }
    }

    switch (baseType) {
      case 'int':
        return "    final $name = (body['${escapeDartString(externalName)}'] as num).toInt();";
      case 'double':
        return "    final $name = (body['${escapeDartString(externalName)}'] as num).toDouble();";
      case 'bool':
        return "    final $name = body['${escapeDartString(externalName)}'] as bool;";
      case 'String':
        return "    final $name = body['${escapeDartString(externalName)}'] as String;";
      default:
        if (baseType.startsWith('List<')) {
          return "    final $name = body['${escapeDartString(externalName)}'] as List<dynamic>;";
        }
        return "    final $name = body['${escapeDartString(externalName)}'];";
    }
  }

  /// Converts a non-null String expression to the target Dart type.
  static String _convertFromString(String varName, String type, String expr) {
    final baseType = type.endsWith('?')
        ? type.substring(0, type.length - 1)
        : type;
    switch (baseType) {
      case 'int':
        return 'final $varName = int.parse($expr);';
      case 'double':
        return 'final $varName = double.parse($expr);';
      case 'bool':
        return 'final $varName = $expr == \'true\';';
      case 'String':
        return 'final $varName = $expr;';
      default:
        return 'final $varName = $expr;';
    }
  }

  /// Converts a nullable String expression to the target Dart type.
  static String _convertFromStringNullable(
    String varName,
    String type,
    String expr,
  ) {
    final baseType = type.endsWith('?')
        ? type.substring(0, type.length - 1)
        : type;
    switch (baseType) {
      case 'int':
        return 'final ${varName}Raw = $expr;\n    final $varName = ${varName}Raw != null ? int.parse(${varName}Raw) : null;';
      case 'double':
        return 'final ${varName}Raw = $expr;\n    final $varName = ${varName}Raw != null ? double.parse(${varName}Raw) : null;';
      case 'bool':
        return "final ${varName}Raw = $expr;\n    final $varName = ${varName}Raw != null ? ${varName}Raw == 'true' : null;";
      case 'String':
        return 'final $varName = $expr;';
      default:
        return 'final $varName = $expr;';
    }
  }

  /// Builds the call arguments string for a method invocation.
  static String _buildCallArgs(List<Map<String, dynamic>> params) {
    return params
        .map((p) {
          final name = p['name'] as String;
          final isNamed = p['isNamed'] == true;
          return isNamed ? '$name: $name' : name;
        })
        .join(', ');
  }
}
