// Generated MCP stdio server
// DO NOT EDIT - automatically generated by mcp_generator

import 'dart:async';
import 'dart:convert';
import 'dart:io' as io;


import 'package:dart_mcp/server.dart';
import 'package:dart_mcp/stdio.dart';



import 'package:mcp_example/src/todo_store.dart' as todo_store;
import 'package:mcp_example/src/user_store.dart' as user_store;

Future<void> main() async {
  final server = MCPServerWithTools(
    stdioChannel(input: io.stdin, output: io.stdout),
  );
  await server.done;
}

base class MCPServerWithTools extends MCPServer with ToolsSupport {
  static const bool _logErrors = false;

  MCPServerWithTools(super.channel)
    : super.fromStreamChannel(
        implementation: Implementation(
          name: 'mcp-server',
          version: '1.0.0',
        ),
        instructions: 'Auto-generated MCP server',
      ) {
    registerTool(
      Tool(
        name: 'createTodo',
        description: 'Create a new todo',
        inputSchema: Schema.object(
    properties: {
      'title': Schema.string(),
    },
    required: ['title'],
  ),
        annotations: ToolAnnotations(readOnlyHint: false, destructiveHint: false, openWorldHint: false),
      ),
      _createTodo,
    );
    registerTool(
      Tool(
        name: 'getTodo',
        description: 'Get todo by ID',
        inputSchema: Schema.object(
    properties: {
      'id': Schema.int(),
    },
    required: ['id'],
  ),
        annotations: ToolAnnotations(readOnlyHint: true, openWorldHint: false),
      ),
      _getTodo,
    );
    registerTool(
      Tool(
        name: 'listTodos',
        description: 'List all todos',
        inputSchema: Schema.object(),
        annotations: ToolAnnotations(readOnlyHint: true, openWorldHint: false),
      ),
      _listTodos,
    );
    registerTool(
      Tool(
        name: 'deleteTodo',
        description: 'Delete a todo',
        inputSchema: Schema.object(
    properties: {
      'id': Schema.int(),
    },
    required: ['id'],
  ),
        annotations: ToolAnnotations(readOnlyHint: false, idempotentHint: true, openWorldHint: false),
      ),
      _deleteTodo,
    );
    registerTool(
      Tool(
        name: 'completeTodo',
        description: 'Mark a todo as completed',
        inputSchema: Schema.object(
    properties: {
      'id': Schema.int(),
    },
    required: ['id'],
  ),
        annotations: ToolAnnotations(readOnlyHint: false, idempotentHint: true, openWorldHint: false),
      ),
      _completeTodo,
    );
    registerTool(
      Tool(
        name: 'assignTodoToUser',
        description: 'Assign a todo to a user',
        inputSchema: Schema.object(
    properties: {
      'todoId': Schema.int(),
      'userId': Schema.int(),
    },
    required: ['todoId', 'userId'],
  ),
        annotations: ToolAnnotations(readOnlyHint: false, idempotentHint: true, openWorldHint: false),
      ),
      _assignTodoToUser,
    );
    registerTool(
      Tool(
        name: 'removeTodoFromUser',
        description: 'Remove a user from a todo',
        inputSchema: Schema.object(
    properties: {
      'todoId': Schema.int(),
      'userId': Schema.int(),
    },
    required: ['todoId', 'userId'],
  ),
        annotations: ToolAnnotations(readOnlyHint: false, idempotentHint: true, openWorldHint: false),
      ),
      _removeTodoFromUser,
    );
    registerTool(
      Tool(
        name: 'getTodosForUser',
        description: 'Get all todos assigned to a user',
        inputSchema: Schema.object(
    properties: {
      'userId': Schema.int(),
    },
    required: ['userId'],
  ),
        annotations: ToolAnnotations(readOnlyHint: true, openWorldHint: false),
      ),
      _getTodosForUser,
    );
    registerTool(
      Tool(
        name: 'createUser',
        description: 'Create a new user',
        inputSchema: Schema.object(
    properties: {
      'name': Schema.string(
      title: 'Full Name',
      description: 'The user\'s full name (1-100 characters)'
    ),
      'email': Schema.string(
      title: 'Email Address',
      description: 'A valid email address for the user',
      pattern: '^[\\w\\.-]+@[\\w\\.-]+\\.\\w+\$'
    ),
    },
    required: ['name', 'email'],
  ),
        annotations: ToolAnnotations(readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false),
      ),
      _createUser,
    );
    registerTool(
      Tool(
        name: 'getUserTodos',
        description: 'Get all todos assigned to a user',
        inputSchema: Schema.object(
    properties: {
      'userId': Schema.int(),
    },
    required: ['userId'],
  ),
        annotations: ToolAnnotations(readOnlyHint: true, openWorldHint: false),
      ),
      _getUserTodos,
    );
    registerTool(
      Tool(
        name: 'getUser',
        description: 'Get user by ID',
        inputSchema: Schema.object(
    properties: {
      'id': Schema.int(),
    },
    required: ['id'],
  ),
        annotations: ToolAnnotations(readOnlyHint: true, openWorldHint: false),
      ),
      _getUser,
    );
    registerTool(
      Tool(
        name: 'listUsers',
        description: 'List all users',
        inputSchema: Schema.object(),
        annotations: ToolAnnotations(readOnlyHint: true, openWorldHint: false),
      ),
      _listUsers,
    );
    registerTool(
      Tool(
        name: 'deleteUser',
        description: 'Delete a user',
        inputSchema: Schema.object(
    properties: {
      'id': Schema.int(),
    },
    required: ['id'],
  ),
        annotations: ToolAnnotations(readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false),
      ),
      _deleteUser,
    );
    registerTool(
      Tool(
        name: 'searchUsers',
        description: 'Search users by query',
        inputSchema: Schema.object(
    properties: {
      'q': Schema.string(
      title: 'Search Query',
      description: 'Text to search for in user names and emails (max 1000 characters)'
    ),
    },
    required: ['q'],
  ),
        annotations: ToolAnnotations(readOnlyHint: true, openWorldHint: false),
      ),
      _searchUsers,
    );
  }

  /// Guards against duplicate initialization requests (e.g. from MCP Inspector
  /// which may send `initialize` more than once for HTTP endpoints).
  bool _isInitialized = false;
  InitializeResult? _initializeResult;

  @override
  FutureOr<InitializeResult> initialize(InitializeRequest request) async {
    if (_isInitialized) return _initializeResult!;
    _isInitialized = true;
    final result = await super.initialize(request);
    _initializeResult = result;
    return result;
  }

  FutureOr<CallToolResult> _createTodo(CallToolRequest request) async {
    try {
    final title = request.arguments!['title'] as String;


      final result = await todo_store.TodoStore.createTodo(title: title);
      return CallToolResult(
        content: [TextContent(text: _serializeResult(result))],
      );
    } catch (e, st) {
      if (_logErrors) {
        io.stderr.writeln('[easy_api] createTodo: $e');
        io.stderr.writeln(st);
        await io.stderr.flush();
      }
      return CallToolResult(
        content: [TextContent(text: 'An error occurred while processing the request.')],
        isError: true,
      );
    }
  }
  FutureOr<CallToolResult> _getTodo(CallToolRequest request) async {
    try {
    final id = request.arguments!['id'] as int;


      final result = await todo_store.TodoStore.getTodo(id);
      return CallToolResult(
        content: [TextContent(text: _serializeResult(result))],
      );
    } catch (e, st) {
      if (_logErrors) {
        io.stderr.writeln('[easy_api] getTodo: $e');
        io.stderr.writeln(st);
        await io.stderr.flush();
      }
      return CallToolResult(
        content: [TextContent(text: 'An error occurred while processing the request.')],
        isError: true,
      );
    }
  }
  FutureOr<CallToolResult> _listTodos(CallToolRequest request) async {
    try {



      final result = await todo_store.TodoStore.listTodos();
      return CallToolResult(
        content: [TextContent(text: _serializeResult(result))],
      );
    } catch (e, st) {
      if (_logErrors) {
        io.stderr.writeln('[easy_api] listTodos: $e');
        io.stderr.writeln(st);
        await io.stderr.flush();
      }
      return CallToolResult(
        content: [TextContent(text: 'An error occurred while processing the request.')],
        isError: true,
      );
    }
  }
  FutureOr<CallToolResult> _deleteTodo(CallToolRequest request) async {
    try {
    final id = request.arguments!['id'] as int;


      final result = await todo_store.TodoStore.deleteTodo(id);
      return CallToolResult(
        content: [TextContent(text: _serializeResult(result))],
      );
    } catch (e, st) {
      if (_logErrors) {
        io.stderr.writeln('[easy_api] deleteTodo: $e');
        io.stderr.writeln(st);
        await io.stderr.flush();
      }
      return CallToolResult(
        content: [TextContent(text: 'An error occurred while processing the request.')],
        isError: true,
      );
    }
  }
  FutureOr<CallToolResult> _completeTodo(CallToolRequest request) async {
    try {
    final id = request.arguments!['id'] as int;


      final result = await todo_store.TodoStore.completeTodo(id);
      return CallToolResult(
        content: [TextContent(text: _serializeResult(result))],
      );
    } catch (e, st) {
      if (_logErrors) {
        io.stderr.writeln('[easy_api] completeTodo: $e');
        io.stderr.writeln(st);
        await io.stderr.flush();
      }
      return CallToolResult(
        content: [TextContent(text: 'An error occurred while processing the request.')],
        isError: true,
      );
    }
  }
  FutureOr<CallToolResult> _assignTodoToUser(CallToolRequest request) async {
    try {
    final todoId = request.arguments!['todoId'] as int;
    final userId = request.arguments!['userId'] as int;


      final result = await todo_store.TodoStore.assignTodoToUser(todoId: todoId, userId: userId);
      return CallToolResult(
        content: [TextContent(text: _serializeResult(result))],
      );
    } catch (e, st) {
      if (_logErrors) {
        io.stderr.writeln('[easy_api] assignTodoToUser: $e');
        io.stderr.writeln(st);
        await io.stderr.flush();
      }
      return CallToolResult(
        content: [TextContent(text: 'An error occurred while processing the request.')],
        isError: true,
      );
    }
  }
  FutureOr<CallToolResult> _removeTodoFromUser(CallToolRequest request) async {
    try {
    final todoId = request.arguments!['todoId'] as int;
    final userId = request.arguments!['userId'] as int;


      final result = await todo_store.TodoStore.removeTodoFromUser(todoId: todoId, userId: userId);
      return CallToolResult(
        content: [TextContent(text: _serializeResult(result))],
      );
    } catch (e, st) {
      if (_logErrors) {
        io.stderr.writeln('[easy_api] removeTodoFromUser: $e');
        io.stderr.writeln(st);
        await io.stderr.flush();
      }
      return CallToolResult(
        content: [TextContent(text: 'An error occurred while processing the request.')],
        isError: true,
      );
    }
  }
  FutureOr<CallToolResult> _getTodosForUser(CallToolRequest request) async {
    try {
    final userId = request.arguments!['userId'] as int;


      final result = await todo_store.TodoStore.getTodosForUser(userId);
      return CallToolResult(
        content: [TextContent(text: _serializeResult(result))],
      );
    } catch (e, st) {
      if (_logErrors) {
        io.stderr.writeln('[easy_api] getTodosForUser: $e');
        io.stderr.writeln(st);
        await io.stderr.flush();
      }
      return CallToolResult(
        content: [TextContent(text: 'An error occurred while processing the request.')],
        isError: true,
      );
    }
  }
  FutureOr<CallToolResult> _createUser(CallToolRequest request) async {
    try {
    final name = request.arguments!['name'] as String;
    final email = request.arguments!['email'] as String;
    if (name.length > 100) {
      return CallToolResult(
        content: [TextContent(text: 'Parameter name exceeds maximum length of 100 characters.')],
        isError: true,
      );
    }
    if (email.length > 254) {
      return CallToolResult(
        content: [TextContent(text: 'Parameter email exceeds maximum length of 254 characters.')],
        isError: true,
      );
    }
    if (!RegExp(r'^[\w\.-]+@[\w\.-]+\.\w+$').hasMatch(email)) {
      return CallToolResult(
        content: [TextContent(text: 'Parameter email does not match required pattern.')],
        isError: true,
      );
    }

      final result = await user_store.UserStore.createUser(name: name, email: email);
      return CallToolResult(
        content: [TextContent(text: _serializeResult(result))],
      );
    } catch (e, st) {
      if (_logErrors) {
        io.stderr.writeln('[easy_api] createUser: $e');
        io.stderr.writeln(st);
        await io.stderr.flush();
      }
      return CallToolResult(
        content: [TextContent(text: 'An error occurred while processing the request.')],
        isError: true,
      );
    }
  }
  FutureOr<CallToolResult> _getUserTodos(CallToolRequest request) async {
    try {
    final userId = request.arguments!['userId'] as int;


      final result = await user_store.UserStore.getUserTodos(userId);
      return CallToolResult(
        content: [TextContent(text: _serializeResult(result))],
      );
    } catch (e, st) {
      if (_logErrors) {
        io.stderr.writeln('[easy_api] getUserTodos: $e');
        io.stderr.writeln(st);
        await io.stderr.flush();
      }
      return CallToolResult(
        content: [TextContent(text: 'An error occurred while processing the request.')],
        isError: true,
      );
    }
  }
  FutureOr<CallToolResult> _getUser(CallToolRequest request) async {
    try {
    final id = request.arguments!['id'] as int;


      final result = await user_store.UserStore.getUser(id);
      return CallToolResult(
        content: [TextContent(text: _serializeResult(result))],
      );
    } catch (e, st) {
      if (_logErrors) {
        io.stderr.writeln('[easy_api] getUser: $e');
        io.stderr.writeln(st);
        await io.stderr.flush();
      }
      return CallToolResult(
        content: [TextContent(text: 'An error occurred while processing the request.')],
        isError: true,
      );
    }
  }
  FutureOr<CallToolResult> _listUsers(CallToolRequest request) async {
    try {



      final result = await user_store.UserStore.listUsers();
      return CallToolResult(
        content: [TextContent(text: _serializeResult(result))],
      );
    } catch (e, st) {
      if (_logErrors) {
        io.stderr.writeln('[easy_api] listUsers: $e');
        io.stderr.writeln(st);
        await io.stderr.flush();
      }
      return CallToolResult(
        content: [TextContent(text: 'An error occurred while processing the request.')],
        isError: true,
      );
    }
  }
  FutureOr<CallToolResult> _deleteUser(CallToolRequest request) async {
    try {
    final id = request.arguments!['id'] as int;


      final result = await user_store.UserStore.deleteUser(id);
      return CallToolResult(
        content: [TextContent(text: _serializeResult(result))],
      );
    } catch (e, st) {
      if (_logErrors) {
        io.stderr.writeln('[easy_api] deleteUser: $e');
        io.stderr.writeln(st);
        await io.stderr.flush();
      }
      return CallToolResult(
        content: [TextContent(text: 'An error occurred while processing the request.')],
        isError: true,
      );
    }
  }
  FutureOr<CallToolResult> _searchUsers(CallToolRequest request) async {
    try {
    final query = request.arguments!['q'] as String;
    if (query.length > 1000) {
      return CallToolResult(
        content: [TextContent(text: 'Parameter query exceeds maximum length of 1000 characters.')],
        isError: true,
      );
    }

      final result = await user_store.UserStore.searchUsers(query);
      return CallToolResult(
        content: [TextContent(text: _serializeResult(result))],
      );
    } catch (e, st) {
      if (_logErrors) {
        io.stderr.writeln('[easy_api] searchUsers: $e');
        io.stderr.writeln(st);
        await io.stderr.flush();
      }
      return CallToolResult(
        content: [TextContent(text: 'An error occurred while processing the request.')],
        isError: true,
      );
    }
  }





  String _serializeResult(dynamic result) {
    if (result == null) return 'null';
    try {
      if (result is Map) return jsonEncode(result);
      if (result is List) {
        final items = result.map((e) {
          if (e == null) return null;
          if (e is Map) return e;
          final toJson = e.toJson;
          if (toJson != null && toJson is Function) return toJson();
          return e.toString();
        }).where((e) => e != null).toList();
        return jsonEncode(items);
      }
      final toJson = result.toJson;
      if (toJson != null && toJson is Function) return jsonEncode(toJson());
      return result.toString();
    } catch (_) {
      return result.toString();
    }
  }
}
